Fixup Clang-Tidy's bugprone-reserved-identifier check failing with CUDA (#7832)
* Fixup Clang-Tidy's bugprone-reserved-identifier check failing with CUDA

Spotted in the CI on the CUDA-11.8-Clang-15 build on ORNL Jenkins
```
/var/jenkins/workspace/Kokkos_PR-7542/core/src/Cuda/Kokkos_Cuda_abort.hpp:31:30: error: declaration uses identifier '__assertfail', which is a reserved identifier [bugprone-reserved-identifier,-warnings-as-errors]
[[noreturn]] __device__ void __assertfail(const void *message, const void *file,
                             ^~~~~~~~~~~~
                             _assertfail

* Suppress clang-tidy warning when defining _CubLog

```
/var/jenkins/workspace/Kokkos_PR-7832/algorithms/src/sorting/./impl/Kokkos_SortByKeyImpl.hpp:50:9: error: declaration uses identifier '_CubLog', which is a reserved identifier [bugprone-reserved-identifier,-warnings-as-errors]
        ^~~~~~~
        CubLog
/var/jenkins/workspace/Kokkos_PR-7832/algorithms/src/sorting/./impl/Kokkos_SortImpl.hpp:54:9: error: declaration uses identifier '_CubLog', which is a reserved identifier [bugprone-reserved-identifier,-warnings-as-errors]
        ^
```

* Fixup annotate new instance of defining _CubLog introduced in develop

Correcting "race condition" :)