core/Cuda: Half_t PR feedback and coverage
  - Address PR feedback:
    - Run volatile tests on device and host
    - Add min() and max() to half_t reduction identity
    - Use iosfwd not iostream in half_t

  - Fix CI build failure and add coverage to unit tests for failure:
    - "error: no matching function for call to 'half_t(const volatile value_type&)'"
    - In order to resolve this we must add a explicit copy constructor since implicit
  copy constructors do not support the volatile type qualifier. As a result,
  std::is_trivially_copyable<half_t> is false now but the byte-level checks
  still pass.

  - Add coverage for volatile operators:
   - Currently supported ops: =, <, <=, >, >=, !=, ==, +=, -=, *=, /=
     half_t types only - no mixed precision.