Prefer atomic_fetch_sub +1 to add -1
```
/__w/kokkos/kokkos/core/src/impl/Kokkos_ConcurrentBitset.hpp(121): error #68: integer conversion resulted in a change of sign
        Kokkos::atomic_fetch_add(const_cast<uint32_t *>(buffer), -1);
                                                                 ^