Fix "missing typename" issue with llvm/15.0.7
Add "typename" to workaround llvm/15.0.7 compilation error that showed up in nightly Trilinos integration testing:

```
18:20:05 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/unit_test/view/TestCreateMirrorViewAndCopy.hpp:22:29: error: missing 'typename' prior to dependent type name 'decltype(original_view_copy)::memory_space'
18:20:05   using copy_memory_space = decltype(original_view_copy)::memory_space;
```

Occurred after changes merged from #9185

Signed-off-by: Nathan Ellingwood <ndellin@sandia.gov>