Enable bugprone-suspicious-stringview-data-usage (#7766)
* Enable bugprone-suspicious-stringview-data-usage check

* Suppress false positive

`argv` is an array of pointers to null terminated strings so it is fine
to use `atoi()` to convert to an integer value.
```
/__w/kokkos/kokkos/benchmarks/launch_latency/launch_latency.cpp:251:24: error: result of a `data()` call may not be null terminated, provide size information to the callee to prevent potential issues [bugprone-suspicious-stringview-data-usage,-warnings-as-errors]
  251 |           N = atoi(arg.data());
      |                    ~~~~^~~~
/__w/kokkos/kokkos/benchmarks/launch_latency/launch_latency.cpp:253:24: error: result of a `data()` call may not be null terminated, provide size information to the callee to prevent potential issues [bugprone-suspicious-stringview-data-usage,-warnings-as-errors]
  253 |           M = atoi(arg.data());
      |                    ~~~~^~~~
/__w/kokkos/kokkos/benchmarks/launch_latency/launch_latency.cpp:255:24: error: result of a `data()` call may not be null terminated, provide size information to the callee to prevent potential issues [bugprone-suspicious-stringview-data-usage,-warnings-as-errors]
  255 |           K = atoi(arg.data());
      |
```