Switch to using functors in sort_by_key_via_sort (#7059)
* Add test for #7036

* Switch to using functors inside function with variadic templates

Otherwise, get errors like
impl/Kokkos_SortByKeyImpl.hpp:210:578: error: could not convert
    ‘& sort_by_key_via_sort<Kokkos::Serial, int*, Kokkos::Serial, float*, Kokkos::Serial>’
    from ‘<unresolved overloaded function type>’
    to ‘void (*)(const Kokkos::Serial&, const Kokkos::View<int*, Kokkos::Serial>&, const Kokkos::View<float*, Kokkos::Serial>&)’
  210 |   Kokkos::parallel_for(

* Update comment